<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Phymnary.SugarPot.AspNetCore</RootNamespace>
    <Version>$(AspPackedVersion)</Version>
  </PropertyGroup>

  <Choose>
    <When Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net10.0'))">
      <PropertyGroup>
        <EfVersion>[10.0.0,)</EfVersion>
      </PropertyGroup>
    </When>
    <Otherwise>
      <PropertyGroup>
        <EfVersion>[8.0.0,)</EfVersion>
      </PropertyGroup>
    </Otherwise>
  </Choose>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" VersionOverride="$(EfVersion)" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" VersionOverride="$(EfVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Phymnary.SugarPot.AspNetCore.Domain\Phymnary.SugarPot.AspNetCore.Domain.csproj" />
  </ItemGroup>

</Project>
