<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Phymnary.SugarPot.AspNetCore</RootNamespace>
    <Version>$(AspPackedVersion)</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Phymnary.SugarPot.AspNetCore.Application\Phymnary.SugarPot.AspNetCore.Application.csproj" />
    <ProjectReference Include="..\roslyn\Phymnary.SugarPot.AspNetCore.Api.Roslyn\Phymnary.SugarPot.AspNetCore.Api.Roslyn.csproj" ReferenceOutputAssembly="false" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)' == 'Release'">
    <None Include="..\roslyn\$(AssemblyName).Roslyn\bin\$(Configuration)\netstandard2.0\$(AssemblyName).Roslyn.dll" Pack="true" Visible="false" PackagePath="analyzers/dotnet/cs" />
  </ItemGroup>

</Project>
